### ISSUE TITLE
Failed to generate expert.pkl

### ISSUE THREAD

**Issue by BravoFr0st** [zbzhu99/NGSIM_SMARTS#6]
**Failed to generate expert.pkl**

Failed to generate `expert.pkl` after running `example_expert_generation.py`.

No pause(Ctrl+Z) occurs in this process.

**Comment by zbzhu99** [comment]
This can be due to the original expert.pkl file being too large... (approximately 5GB):

**Comment by zbzhu99** [comment]
This can be due to the original `expert.pkl` file being too large... (approximately 5GB).
Here is the link to the file: https://jbox.sjtu.edu.cn/l/s1yZkP

The raw observation return from SMARTS may contain massive useless features. Now I provide an example observation_adapter in this repo and can only save the adapted observation to .pkl file. You can customize the adapter depending on the features you want to use.
